task_pesquisar:
  description: >
    Realize uma pesquisa profunda sobre o tema '{topic}' em fontes confiáveis, como artigos peer-reviewed,
    bases como arXiv, PubMed, SciELO, Semantic Scholar ou CrossRef. Liste os dados coletados com suas referências.

    Pergunta:
    {topic}

  expected_output: >
    Lista detalhada de dados e suas respectivas fontes confiáveis.

  agent: agente_pesquisador

task_analizar_texto:
  description: >
    Analise criticamente os dados fornecidos. Elimine duplicidades e dados questionáveis.
    Destaque os pontos-chave mais relevantes que devem ser considerados na redação de um artigo científico sobre '{topic}'.

  expected_output: >
    Resumo analítico das principais informações, com justificativas e contexto.

  agent: agente_analista

task_resumir_texto:
  description: >
    Com base na análise feita, elabore um resumo técnico e preciso das descobertas. 
    Organize as ideias com clareza e linguagem científica acessível. Mantenha fidelidade às fontes.

  expected_output: >
    Resumo técnico claro e estruturado para uso em artigo científico.

  agent: agente_resumo

task_formatar_artigo:
  description: >
    Converta o resumo técnico em um artigo científico completo, estruturado com: Introdução, Metodologia, 
    Resultados, Discussão e Conclusão. Utilize estilo de escrita acadêmico, respeitando normas da ABNT ou APA.

  expected_output: >
    Texto final do artigo científico formatado segundo padrões editoriais brasileiros, em português.

  agent: agente_artigo